language: node_js
node_js:
    - 6
    - 8
    - 10
    - 12
    - 14

branches:
    only:
        - master

install:
    - command -v 2>&1 >/dev/null npx || npm install --global npx
    - make -B install

script:
    - make all
    - make coverage
